### ISSUE TITLE
Paths variable does not get correctly set

### ISSUE THREAD

**Issue by e-alfred** [mediapeers/ansible-role-filebeat#2]
Hello,

I am running this playbook but the paths variable for the prospector isn't set correctly:

```
- name: Deploy Filebeat and send logs to Graylog server
  hosts: myserver
  vars:
    - filebeat_logstash_server: 'myserver'
    - filebeat_logstash_server_port: 5044
    - filebeat_logstash_tls_insecure: true
    - filebeat_logstash_tls: true 
    - filebeat_prospectors:
      - { paths: "/var/log/*/*.log", input_type: log, document_type: log}
  roles:
    - mediapeers.filebeat
```

On the machine it gets deployed to the filebeat.yml file is created like that:

```
 prospectors:
    # Each - is a prospector. Below are the prospector specific configurations
    -
      document_type: log
      input_type: log
      paths  - /var/log/*/*.log
```

instead of

```
 prospectors:
    # Each - is a prospector. Below are the prospector specific configurations
    -
      document_type: log
      input_type: log
      paths  
        - /var/log/*/*.log
```
